spring:
  datasource:
    diver-class-name: org.postgresql.Driver
    url:
    username:
    password:
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true

