spring:
  datasource:
    diver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
