server.port: 8080

spring:
  datasource:
    diver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true